"""
Pydantic模式模块
"""

from app.schemas.k8s_schemas import (
    # 认证
    TokenUser,
    TokenPayload,
    # 通用
    ErrorResponse,
    SuccessResponse,
    K8SResourceMetadata,
    K8SResourceListResponse,
    # Pod
    PodInfo,
    PodListResponse,
    PodLogRequest,
    PodLogResponse,
    PodExecRequest,
    # Service
    ServicePort,
    ServiceInfo,
    ServiceListResponse,
    ServiceCreateRequest,
    ServiceUpdateRequest,
    # Ingress
    IngressPath,
    IngressRule,
    IngressTLS,
    IngressInfo,
    IngressListResponse,
    IngressCreateRequest,
    IngressUpdateRequest,
    IngressSimpleCreateRequest,
    IngressExternalCreateRequest,
    # Secret
    SecretInfo,
    SecretListResponse,
    SecretCreateRequest,
    SecretUpdateRequest,
    # ConfigMap
    ConfigMapInfo,
    ConfigMapListResponse,
    ConfigMapCreateRequest,
    ConfigMapUpdateRequest,
    # Deployment
    DeploymentInfo,
    DeploymentListResponse,
    DeploymentCreateRequest,
    DeploymentUpdateRequest,
    DeploymentScaleRequest,
    ContainerSpec,
    # StatefulSet
    StatefulSetInfo,
    StatefulSetListResponse,
    # DaemonSet
    DaemonSetInfo,
    DaemonSetListResponse,
    # Job
    JobInfo,
    JobListResponse,
    # CronJob
    CronJobInfo,
    CronJobListResponse,
    # PVC
    PVCInfo,
    PVCListResponse,
    # 项目资源
    ProjectResourcesResponse,
    # Pod容器
    ContainerInfo,
    PodContainersResponse,
)

__all__ = [
    "TokenUser",
    "TokenPayload",
    "ErrorResponse",
    "SuccessResponse",
    "K8SResourceMetadata",
    "K8SResourceListResponse",
    "PodInfo",
    "PodListResponse",
    "PodLogRequest",
    "PodLogResponse",
    "PodExecRequest",
    "ServicePort",
    "ServiceInfo",
    "ServiceListResponse",
    "ServiceCreateRequest",
    "ServiceUpdateRequest",
    "IngressPath",
    "IngressRule",
    "IngressTLS",
    "IngressInfo",
    "IngressListResponse",
    "IngressCreateRequest",
    "IngressUpdateRequest",
    "IngressSimpleCreateRequest",
    "IngressExternalCreateRequest",
    "SecretInfo",
    "SecretListResponse",
    "SecretCreateRequest",
    "SecretUpdateRequest",
    "ConfigMapInfo",
    "ConfigMapListResponse",
    "ConfigMapCreateRequest",
    "ConfigMapUpdateRequest",
    "DeploymentInfo",
    "DeploymentListResponse",
    "DeploymentCreateRequest",
    "DeploymentUpdateRequest",
    "DeploymentScaleRequest",
    "ContainerSpec",
    "StatefulSetInfo",
    "StatefulSetListResponse",
    "DaemonSetInfo",
    "DaemonSetListResponse",
    "JobInfo",
    "JobListResponse",
    "CronJobInfo",
    "CronJobListResponse",
    "PVCInfo",
    "PVCListResponse",
    "ProjectResourcesResponse",
    "ContainerInfo",
    "PodContainersResponse",
]