name: 'openvpn_service'
services:
  openvpn_server_01:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_01
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER=true
      - MASTER_GW=200.64.0.1
      - MASTER_IP=200.64.0.2
      - PORT=1194
      - NET_START=200.64.0.100
      - NET_END=200.64.7.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn.sh
    depends_on:
      - nginx_frontend

  openvpn_server_02:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_02
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1195
      - NET_START=200.64.8.0
      - NET_END=200.64.15.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn.sh
    depends_on:
      - openvpn_server_01

  openvpn_server_03:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_03
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1196
      - NET_START=200.64.16.0
      - NET_END=200.64.23.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn.sh
    depends_on:
      - openvpn_server_02

  openvpn_server_04:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_04
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1197
      - NET_START=200.64.24.0
      - NET_END=200.64.31.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn.sh
    depends_on:
      - openvpn_server_03

  openvpn_server_tcp_01:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_tcp_01
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1194
      - NET_START=200.64.32.0
      - NET_END=200.64.39.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn_tcp.sh
    depends_on:
      - openvpn_server_04

  openvpn_server_tcp_02:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_tcp_02
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1195
      - NET_START=200.64.40.0
      - NET_END=200.64.47.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn_tcp.sh
    depends_on:
      - openvpn_server_tcp_01

  openvpn_server_tcp_03:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_tcp_03
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1196
      - NET_START=200.64.48.0
      - NET_END=200.64.55.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn_tcp.sh
    depends_on:
      - openvpn_server_tcp_02

  openvpn_server_tcp_04:
    image: kylemanna/openvpn:latest
    restart: always
    container_name: openvpn_server_tcp_04
    network_mode: "service:nginx_frontend"
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - MASTER_IP=200.64.0.2
      - PORT=1197
      - NET_START=200.64.56.0
      - NET_END=200.64.63.255
    volumes:
      - ../data:/data
      - ../data/cert:/etc/openvpn
      - ./vpn-status/openvpn:/tmp/openvpn
    entrypoint:
      - /data/entrypoint_openvpn_tcp.sh
    depends_on:
      - openvpn_server_tcp_03

  vpn_server:
    build:
      context: vpn_server
      dockerfile: Dockerfile
    restart: always
    container_name: vpn_server
    network_mode: "service:nginx_frontend"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../data:/data
    depends_on:
      - openvpn_server_04

  nginx_frontend:
    image: nginx:latest
    restart: always
    container_name: nginx_frontend
    hostname: nginx_frontend
    networks:
      - openvpn_network
    ports:
      - 11194:1194/tcp
      - 11194:1194/udp
      - 11195:1195/tcp
      - 11195:1195/udp
      - 11196:1196/tcp
      - 11196:1196/udp
      - 11197:1957/tcp
      - 11197:1197/udp
      - 8080:8079/tcp # for vpn file server
      - 11193:8848/tcp #for nacso api
      - 8082:8082/tcp #for nacos console
      - 8001:8001/tcp #for higress
      - 8081:8080/tcp #for higress
      - 8443:8443/tcp #for higress
      - 8079:80/tcp #for vpn-sstatus-web page
      - 8078:8078/tcp #for vpn-sstatus-web page
    environment:
      - TZ=Asia/Shanghai
      - MAP_LIST=11194:1194 11195:1195 11196:1196 11197:1197
    volumes:
      - ../data:/data
      - ../data/nginx.conf:/etc/nginx/nginx.conf
    entrypoint:
      - /data/entrypoint_nginx.sh

  nacos:
    image: nacos/nacos-server:latest
    restart: always
    container_name: nacos
    environment:
      - MODE=standalone # 指定为单机模式
      - TZ=Asia/Shanghai
      - NACOS_AUTH_TOKEN=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
      - NACOS_AUTH_IDENTITY_KEY=abcdefg
      - NACOS_AUTH_IDENTITY_VALUE=abcdefg
      - NACOS_AUTH_ENABLE=false
      - NACOS_CONSOLE_PORT=8082
    network_mode: "service:nginx_frontend"
    volumes:
      - ./nacos_data/:/home/nacos/data # 挂载数据目录以持久化数据

  higress-ai:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
    restart: always
    container_name: higress-ai
    environment:
      - TZ=Asia/Shanghai
    network_mode: "service:nginx_frontend"
    volumes:
      - ./higress/:/data # 挂载数据目录以持久化数据
    env_file:
      - higress/default.cfg
    depends_on:
      - higress-redis

  higress-redis:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/redis-stack-server:7.4.0-v3
    restart: always
    container_name: higress-redis
    environment:
      - TZ=Asia/Shanghai
    network_mode: "service:nginx_frontend"
    depends_on:
      - openvpn_server_04

  mcp-server-ssh:
    image: runshine0819/mcp-ssh:latest
    restart: always
    container_name: mcp-server-ssh
    network_mode: "service:nginx_frontend"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../data:/data
    depends_on:
      - openvpn_server_04

  vpn-status:
    image: runshine0819/openvpn-status-web:latest
    restart: always
    container_name: vpn-status
    network_mode: "service:nginx_frontend"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./vpn-status/openvpn:/tmp/openvpn
      - ./vpn-status/openvpn-status-web/config.yaml:/etc/openvpn-status-web/config.yml
    depends_on:
      - openvpn_server_04

  nginx_service:
    image: nginx:latest
    restart: always
    container_name: nginx_service
    hostname: nginx_service
    networks:
      openvpn_network:
        ipv4_address: 200.64.0.4
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../data:/data
      - ../data/conf/nginx/nginx_service.conf:/etc/nginx/nginx.conf

networks:
  openvpn_network:
    driver: bridge
    enable_ipv6: false
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 200.64.0.0/16





