apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-local-path-pvc
  namespace: sothothv2-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi