apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  namespace: sothothv2-ns
spec:
  type: ClusterIP   # 或者不写，默认是ClusterIP
  selector:
    name: cloudbeaver   # 这里必须和Deployment中Pod的标签匹配
  ports:
    - port: 80
      targetPort: 8978
      protocol: TCP
      name: http