apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-storage-pvc
  namespace: default  # 根据实际情况修改命名空间
spec:
  accessModes:
    - ReadWriteMany  # 或 ReadWriteOnce，根据NFS配置决定
  storageClassName: nfs-storage-192.168.13.66
  resources:
    requests:
      storage: 20Gi  # 根据需求调整存储大小