apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-service
  namespace: default
  annotations:
    metallb.io/allow-shared-ip: "shared-192.168.12.90"   # 可选：允许IP共享
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  type: LoadBalancer
  selector:
    component: mysqlrouter
    mysql.oracle.com/cluster: mysql-cluster
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  # 关键：在spec中指定loadBalancerIP
  loadBalancerIP: "192.168.12.90"  # 必须在static-ips-pool范围内

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
  namespace: default
spec:
  selector:
    component: mysqlrouter
    mysql.oracle.com/cluster: mysql-cluster
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

