apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-secret
type: generic
data:
  # 密码使用base64编码，实际使用时替换
  rootUser: cm9vdA==             #root
  rootHost: JQ==                 # %
  rootPassword: SHVhd2VpMTIjJA== #Huawei12#$
