apiVersion: apps/v1
kind: Deployment
metadata:
  name: secflow-platform-frontend
  namespace: secflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secflow-platform-frontend
  template:
    metadata:
      labels:
        name: secflow-platform-frontend
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: secflow-platform-frontend
        image: runshine0819/secflow-frontend:amd64-20260329-f9b4012  # 当前开发环境实际运行镜像
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: secflow-platform-frontend-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: secflow-platform-frontend-config
            mountPath: /usr/share/nginx/html/config.js
            subPath: config.js
        livenessProbe:
          httpGet:
            path: /api/frontend/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/frontend/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        # 资源限制
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
      - name: secflow-platform-frontend-config
        configMap:
          name: secflow-platform-frontend-config
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: config.js
              path: config.js
