apiVersion: v1
kind: ServiceAccount
metadata:
  name: secflow-app-binary-evolution-center-serviceaccount
  namespace: secflow-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secflow-app-binary-evolution-center-discovery-role
  namespace: secflow-ns
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secflow-app-binary-evolution-center-discovery-binding
  namespace: secflow-ns
subjects:
  - kind: ServiceAccount
    name: secflow-app-binary-evolution-center-serviceaccount
    namespace: secflow-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secflow-app-binary-evolution-center-discovery-role
