apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secflow-platform-mysql-data-pvc
  namespace: secflow-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
