apiVersion: apps/v1
kind: Deployment
metadata:
  name: secflow-platform-resource
  namespace: secflow-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: secflow-platform-resource
  template:
    metadata:
      labels:
        name: secflow-platform-resource
    spec:
      serviceAccountName: secflow-platform-resource-serviceaccount
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: secflow-platform-resource
        image: ghcr.io/runshine/secflow-platform-resource:latest  # 包含kubectl命令
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secflow-platform-menu-config
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: secflow-platform-resource-data-nfs-pvc
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/resource/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/resource/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30

      volumes:
      - name: secflow-platform-resource-data-nfs-pvc
        persistentVolumeClaim:
          claimName: secflow-platform-resource-data-nfs-pvc  # 引用PVC
      - name: secflow-platform-menu-config
        configMap:
          name: secflow-platform-menu-config
          items:
            - key: config.yaml
              path: config.yaml
