apiVersion: v1
kind: Service
metadata:
  name: secflow-app-dataflow-vuln-scanner
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    app: secflow-app-dataflow-vuln-scanner
    role: manager
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secflow-app-dataflow-vuln-scanner
