apiVersion: v1
kind: Service
metadata:
  name: secflow-platform-redis
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: secflow-platform-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
