apiVersion: v1
kind: Service
metadata:
  name: secflow-platform-ai-agent-framework
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: "secflow-platform-ai-agent-framework"
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secflow-platform-ai-agent-framework
