apiVersion: v1
kind: Service
metadata:
  name: secflow-platform-mysql
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: secflow-platform-mysql
    tier: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
