apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secflow-platform-vuln-data-nfs-pvc
  namespace: secflow-ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage-192.168.13.66
