apiVersion: apps/v1
kind: Deployment
metadata:
  name: secflow-platform-workflow-status
  namespace: secflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secflow-platform-workflow-status
  template:
    metadata:
      labels:
        name: secflow-platform-workflow-status
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: secflow-platform-workflow-status
        image: runshine0819/secflow-platform-workflow-status:latest
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secflow-platform-workflow-status-config
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/workflow-status/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/workflow-status/ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30

      volumes:
      - name: secflow-platform-workflow-status-config
        configMap:
          name: secflow-platform-workflow-status-config
          items:
            - key: config.yaml
              path: config.yaml
