apiVersion: apps/v1
kind: Deployment
metadata:
  name: secflow-app-dataflow-analyse
  namespace: secflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secflow-app-dataflow-analyse
  template:
    metadata:
      labels:
        name: secflow-app-dataflow-analyse
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: secflow-app-dataflow-analyse
        image: 172.31.30.52:5000/secflow-app-dataflow-analyse:latest
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: PORT
            value: "8080"
          - name: SERVICE_YAML
            value: /app/service.yaml
          - name: FILESERVER_ROOT
            value: /data/files
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secflow-app-dataflow-analyse-config
          mountPath: /app/service.yaml
          subPath: service.yaml
        - name: secflow-platform-fileserver-data-nfs-pvc
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/app/dataflow-analyse/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/app/dataflow-analyse/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: secflow-app-dataflow-analyse-config
        configMap:
          name: secflow-app-dataflow-analyse-config
          items:
            - key: service.yaml
              path: service.yaml
      - name: secflow-platform-fileserver-data-nfs-pvc
        persistentVolumeClaim:
          claimName: secflow-platform-fileserver-data-nfs-pvc
