apiVersion: v1
kind: Service
metadata:
  name: secflow-platform-static-binary
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: "secflow-platform-static-binary"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: secflow-platform-static-binary