apiVersion: v1
kind: Service
metadata:
  name: secflow-app-firmware-unpacker
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: secflow-app-firmware-unpacker
    component: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secflow-app-firmware-unpacker
