apiVersion: v1
kind: Service
metadata:
  name: secflow-app-entry-analyse
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: "secflow-app-entry-analyse"
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secflow-app-entry-analyse
