apiVersion: v1
kind: ServiceAccount
metadata:
  name: secflow-app-firmware-unpacker-serviceaccount
  namespace: secflow-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secflow-app-firmware-unpacker-pod-reader
  namespace: secflow-ns
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secflow-app-firmware-unpacker-pod-reader-binding
  namespace: secflow-ns
subjects:
  - kind: ServiceAccount
    name: secflow-app-firmware-unpacker-serviceaccount
    namespace: secflow-ns
roleRef:
  kind: Role
  name: secflow-app-firmware-unpacker-pod-reader
  apiGroup: rbac.authorization.k8s.io
