apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secflow-app-kernel-scan-data-nfs-pvc
  namespace: secflow-ns
spec:
  storageClassName: nfs-storage-192.168.13.66
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
