apiVersion: v1
kind: Service
metadata:
  name: secflow-app-binary-security
  namespace: secflow-ns
spec:
  type: ClusterIP
  selector:
    name: secflow-app-binary-security
    role: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: secflow-app-binary-security
