apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: sothothv2-ns
  annotations:
    # 启用 HTTPS 重定向（如果需要）
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # 如果需要 websocket 支持
    nginx.ingress.kubernetes.io/websocket-services: "kibana-kb-http"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "kibana-kb-http.sothothv2-ns.svc.cluster.local"
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kibana.sothothv2.com
      secretName: wildcard-sothothv2.com-tls
  rules:
    - host: kibana.sothothv2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
