apiVersion: apps/v1
kind: Deployment
metadata:
  name: sothoth-server
  namespace: sothoth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sothoth-server
  template:
    metadata:
      labels:
        name: sothoth-server
    spec:
      serviceAccountName: sothoth-server
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: sothoth-server
        image: ultramangaia/gaiasec-env:server
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        workingDir: /app
        volumeMounts:
        - name: file-cache-storage
          mountPath: /app/file-cache
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2"
          limits:
            memory: "2048Mi"
            cpu: "8"
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root123
          - name: MYSQL_DATABASE
            value: gaiasec
          - name: MYSQL_USER
            value: sa
          - name: MYSQL_PASSWORD
            value: qq123456
        volumeMounts:
        - name: sothoth-local-storge
          mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
        # 资源限制
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "2"

      volumes:
      - name: file-cache-storage
        persistentVolumeClaim:
          claimName: sothoth-nfs-pvc
      - name: sothoth-local-storge
        persistentVolumeClaim:
          claimName: sothoth-local-pvc
