apiVersion: v1
kind: Service
metadata:
  name: sothoth-server
  namespace: sothoth
spec:
  type: ClusterIP
  selector:
    name: "sothoth-server"
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP


