apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sothoth-local-pvc
  namespace: sothoth
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-192.168.13.66
  resources:
    requests:
      storage: 10Gi