apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gaiasec-ingress
  namespace: sothoth
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "nginx-server"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upstream-vhost: "gaiasec.819819.xyz"
spec:
  ingressClassName: nginx
  rules:
  - host: gaiasec.sothothv2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-server
            port:
              number: 80

