# NFS PersistentVolume
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nfs-pv
      namespace: sothothv2-ns
    spec:
      capacity:
        storage: 100Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: nfs-storage
      nfs:
        #server: <NFS_SERVER_IP>  # 替换为您的NFS服务器IP
        #path: "/path/to/nfs/share"  # 替换为您的NFS共享路径
        server: 192.168.13.66
        path: /nvme/share_k8s
  - # NFS PersistentVolumeClaim
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: file-server-nfs-pvc
      namespace: sothothv2-ns
    spec:
      storageClassName: nfs-storage
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 20Gi