apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sothothv2-client-script-service-nfs-pvc
  namespace: sothothv2-ns
spec:
  storageClassName: nfs-storage-192.168.13.66
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi