apiVersion: v1
kind: Service
metadata:
  name: client-script-service
  namespace: sothothv2-ns
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"  # 可选：允许IP共享
spec:
  type: LoadBalancer
  selector:
    name: "client-script-service"
  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP
      name: client-script-service
  loadBalancerIP: "192.168.12.90"  # 必须在static-ips-pool范围内