apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chirmera-platform-schedule
  namespace: secflow-ns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chirmera-platform-schedule
