# listen address and port
host: "0.0.0.0"
port: "8078"
# optional: drop priviliges in case you want to but you should give this user at least read access on the log files
user: "root"
group: "root"
# logfile is optional, logs to STDOUT else
logfile: "openvpn-status-web.log"
# hash with each VPNs display name for humans as key and further config as value
vpns:
  udp-openvpn-server-11194:
    # the status file path and status file format version are required
    version: 1
    status_file: "/tmp/openvpn/openvpn-1194-status.log"
  udp-openvpn-server-11195:
    # the status file path and status file format version are required
    version: 1
    status_file: "/tmp/openvpn/openvpn-1195-status.log"
  udp-openvpn-server-11196:
    # the status file path and status file format version are required
    version: 1
    status_file: "/tmp/openvpn/openvpn-1196-status.log"
  udp-openvpn-server-11197:
    # the status file path and status file format version are required
    version: 1
    status_file: "/tmp/openvpn/openvpn-1197-status.log"