apiVersion: v1
kind: Service
metadata:
  name: agent-service-manager
  namespace: sothothv2-ns
spec:
  type: ClusterIP
  selector:
    name: "agent-service-manager"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

