# storageclass-nfs.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-192.168.13.66
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"  # 删除PVC时是否归档数据
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true  # 是否允许扩容