apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUYEIwDbeogt3LYJcvopeicyy5+b8wDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI1MTIwOTAxNDgyMFoYDzIxMjUxMTE1MDE0ODIwWjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCrU2vlX2YxzZhFUvKDfCjmvtscw4B98EISfm/DSdhW
    OjnXXzhqz2gGuR0M3E/G3DcIJRS1hGputt2C21QZxcUCrltikrLXKEfk3DLtj7t5
    PLlzhD5Y0qMJwfvomOBG927FQ53y7Z8W5QTu923jSo746LlWgM4EUVJhVdZBGEHo
    X8o+b4wGzLGHc0jipM21LoAFu/S7SbYn8KiU+DOv8q8ng3z9etdQPLOO3TfM2vh6
    Z0wa+bn3M6k5yxN7XRCAPqInBa7EPvHgM3krDKR9Rck7yo5Q1O/sgXdS/eoEDPuC
    X6GeMetqCV+hHhzX3mRlyv05wd3DzKMI0yQnVuzcKDB24leIR3ieAGGIR4ZjN819
    OXVKYrD5V+7ziCoEwd4IbE0tUb4ReiTFW3CHIqZqrX+eGGEcnfj9mnbpspSgZRlc
    ixXStK3lzP++gzDs7WMsRQ9f5b0Jmd6q3hWlj/uWCmc1ne5cJThdg870kH+kckJs
    /YdO2YcEUGsHTggtpNHUfuq9Xp+2myb4UZA9pc5U7v5dpDH0g3uIwVMURNJN8tct
    Z3k6uT2cFs/MrhC6gQebVsO/hHk71FWbtKHzsSCQe7d+cQ6+IbG2yoiM9xpra3SI
    ILqG4zgrcfTtSiQ64U2t2IZBZ0pKVHIJnJZzWm2qzM7qiAFuowU9kS65INzn/bci
    ewIDAQABo1MwUTAdBgNVHQ4EFgQU+vk/2Lr9iHvIAsiRr0DDyIP04kgwHwYDVR0j
    BBgwFoAU+vk/2Lr9iHvIAsiRr0DDyIP04kgwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAiXQoSs+pLozz1i5gs2f2TUJ0utLWSSppomNhIHSsCg8M
    4ZBXAT90FqGkBVgCHrt+wNOxmkd5IvTPUsG6+sKC2KUMwg5nmYGvLHOphmwEwlwE
    7nYmeIGnyl1oLRuICMTvZU601QnCJ+6nC3HGycsv7laptib3y9Tc2nlhqJALPh9t
    738X4YkwbKq4DH3AbJTWSCoduhmYRc8sNJd6LuzPL8ZqaF84mPatrG8wsYLar9Sj
    LnsznhqpBFMFK8DzqXRgdE4hmMsB3GhDE70uv+vl3KnLnunIL5mFOH+I0QDqC4v0
    qyPJI8i8hJwdpn2AAJ8V4iCUdwMi6C63Dtt3mdpKkKsBG7M5vFa5P7iCxMq583uO
    CQVByhu7i7F4eL2YiersYA5TGkFrhDZXxwjuPVdpxpNlKfgSi7kXRf7MbB7UFHUa
    huLu3Qd6gHWrlGh0FBFF0dc8V+vxEZgb7dWbphkjqpNZ1vAc/RktXfIb/wdqBt0P
    FQKXugnkYve2FbRUEKZ/Y8R8B7WsUjLzQCba/TS5eozZfnTGm5Lrljw9y84tQjmi
    RAG9pJ+jAHZWl9E2KS/nZx/ctaJFOrvrh8ZL0gLVRMSl1AhdWH4rk9Bc2yxQLz17
    cl7uRNHaB9nWYI5Vfx5eR5lQAj4a/lRQtCWHpuAIO62ok/JlG2RosQYCPiaMBuc=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-28T14:53:03Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2025-12-09T01:48:26Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "7"
