apiVersion: v1
data:
  cert: |
    acmeIssuer:
    - ak: ""
      email: your82216@yours59840.com
      name: letsencrypt
      sk: ""
    automaticHttps: true
    credentialConfig: []
    fallbackForInvalidSecret: false
    renewBeforeDays: 30
    version: "20250728111846"
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-28T11:18:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:cert: {}
    manager: higress
    operation: Update
    time: "2025-07-28T11:18:46Z"
  name: higress-https
  namespace: higress-system
  resourceVersion: "1"
