apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUFZrMFtWiGW8SxwdVdUcOXMOHwMUwDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI1MDgyODA2MDA1NloYDzIxMjUwODA0MDYwMDU2WjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCiZe0unIyxlId4MtIaobPS66hKF7HtApTBlTkzvl8G
    DOjAft0W2N3KwpHj/hTWIiVNVycRIed3vJrog49mrhylgRii5cJB5VbLPsk5ite2
    qvpIwk2ti+JZeagq8e6j9v9mr3qVr2pJAhEcn/UWp8eKokk/7osUeSFUxPOEhK1E
    UY1XGndggZrCEpOo4SNdeXV0Kdy3M+4AheRf/qaJa8CgDhuA0ije36++/IRwQXgW
    ITOdWQGiQotg5gaYS7GrAz4ZNaD7T/tsxFWyMrYYGJrJXnpfwxZFMjG2mqWA17Zw
    6VmAYQqB+BbfrTMU4lFjucqLhcpSqWXBitCKm29UrKnyzupMaKOL0dJtBPCmB3s8
    jGKDe0ZvgFdgQ5lbGv1JQ40ZryNJQUtndp349NQhx0PE5Fozvq1RPmer3yV5uyiK
    EWEqtbMIKnNkNazP4uWIzm7L4ryIA5DGXRiU5xBiScccKerG0GDT2u2XpkLKQOse
    SuBAyL1V7PF63VMsc0ntdlkX3VIq3NCBMLPeN26bJ87zP38Dq561lwrtqQQ+MjAu
    itSZEdZFSfNt4Ah9esetxatWx9Cd6PwUuLDHqCeIUhgoh0/7aBCo1D6Tc28Ab2wl
    6CN3yEUAUcZrWh5mj8kR1h8gX0/EU9+SxaFhEhJNo59ytwE2YHf+nke95bmOWM0U
    bQIDAQABo1MwUTAdBgNVHQ4EFgQU/khgQVYKjphEyyLU43BvFDmmhtUwHwYDVR0j
    BBgwFoAU/khgQVYKjphEyyLU43BvFDmmhtUwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAgoCgzm9t2H4vrXlRNOrABHf6qggjDnPSlL7pAm5cHIEl
    nTyTZ1PU/pSZKh5Pv19UNZXwnt1hw8OAVqeasy8i7QiSxJGFlileZ9fniU/7ft/j
    c+5O+VChLnW/cLoX7Anq43doHDLVEW70hE9XGihMGzWZ1WD+khDPy7YvrWFfrlBp
    d9+lRYVCPzubWLAxnXIORDiOqEBuTK41sZ3o08+t/8nhV20V5w0qCTuUnCPMpc+n
    mBGvTLdSEUufPrAutLwgDnEF6+2UFgAjeJhhW4B8yAlMR9FgDhjv4XquOR2gC1Bt
    Sy+XaXPv+HnHqQpVZuq3xzaXW52Vecs5cV38Y7e5uJT8rCJ+HMFXsBrMhAiKbLW6
    5Zb65Y1K/rz8osY1gZl3JPvROz0XeJj+vJFQ6AbcTy7AdA5R1qoSxkb1iBPAzzgJ
    siMmlUYXP/Yk0WAhnb3LTkr8kghX2uItcE1ehA8mmKJZZu7fyV7wCgC6dJaMM/YN
    eN9YikTndyZaOfUtXHIHRvaLDsbbR9Th05YY0ryHQ+uhUb1kTQSoBHQYSHMX3fm6
    ci0hOULbw5Urt9SWgRpc6aI27n2EE06WiCBjCkU2oXWwQ9RQgQKCsf5hhKbrmz+k
    FIG38Ne2PGYM2X02jFw3gFfPvmSXO/CbucrVTDIJ61bLiM+f07cOv5mzAB5rA2I=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-28T14:53:03Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2025-08-28T06:01:00Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "4"
