apiVersion: v1
data:
  dashboard.builtin: "true"
  index.redirect-target: /ai/route
  mode: standalone
  route.default.initialized: "true"
  system.initialized: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2000-01-01T00:00:00Z"
  labels:
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:dashboard.builtin: {}
        f:route.default.initialized: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2025-07-28T11:18:52Z"
  name: higress-console
  namespace: higress-system
  resourceVersion: "8"
