apiVersion: v1
kind: Service
metadata:
  name: vscode-web-manager
  namespace: sothothv2-ns
spec:
  type: ClusterIP
  selector:
    name: "vscode-web-manager"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


