name: 'jaeger_service'
services:
  jaeger_all_in_one:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
    restart: always
    container_name: jaeger_all_in_one
    network_mode: bridge
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 5778:5778
      - 9411:9411
    environment:
      - TZ=Asia/Shanghai
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    volumes:
      - ../data:/data



#https://www.jaegertracing.io/docs/1.6/getting-started/



