from __future__ import annotations

import time
from pathlib import Path

from app.core.config import get_config
from app.core.time_utils import utc_now_z
from app.workers.runner import (
    StageArtifact,
    StageContext,
    StageExecutionResult,
    StageHooks,
    append_file_to_log,
    build_agentflow_exec_command,
    build_agentflow_node,
    build_agentflow_process_env_and_summary,
    build_codex_exec_command,
    build_opencode_exec_command,
    build_process_env_and_summary,
    command_line_string,
    copy_file,
    discover_single_run_dir,
    extract_opencode_session_id,
    opencode_last_event_is_error,
    project_label,
    read_json_file,
    resolve_executor_mode,
    resolve_stage_primary_report_output_path,
    resolve_stage_executor_model,
    resolve_stage_work_dir,
    run_logged_command,
    write_json_file,
    write_last_message_from_agentflow_result,
    write_last_message_from_jsonl,
    write_text_file,
)


def run_audit_stage(context: StageContext, hooks: StageHooks) -> StageExecutionResult:
    cfg = get_config().execution
    audit_skill = str(context.effective_config.get("audit_skill") or cfg.default_audit_skill)
    executor_mode = resolve_executor_mode(context.effective_config)
    executor_model = resolve_stage_executor_model(context)
    prompt_path = context.stage_session_file("prompt.txt")
    events_path = context.stage_session_file("events.jsonl")
    last_message_path = context.stage_session_file("last-message.md")
    final_report_path = resolve_stage_primary_report_output_path(
        context,
        "audit",
        default_path=context.stage_artifact_path("audit-report.md"),
    )
    log_path = context.stage_log_path()
    work_dir = resolve_stage_work_dir(context)
    prompt_project_path = str(work_dir) if context.project_path else ""
    prompt = _build_prompt(
        audit_skill=audit_skill,
        repo_root=context.repo_root,
        project_path=prompt_project_path,
        output_report_path=_attempt_output_path(context),
    )
    write_text_file(prompt_path, prompt)

    if executor_mode == "mock":
        return _run_mock_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
        )
    if executor_mode == "opencode_cli":
        return _run_opencode_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
            executor_model=executor_model,
        )
    if executor_mode == "agentflow_cli":
        return _run_agentflow_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
            executor_model=executor_model,
        )
    return _run_codex_stage(
        context=context,
        hooks=hooks,
        prompt=prompt,
        prompt_path=prompt_path,
        events_path=events_path,
        last_message_path=last_message_path,
        final_report_path=final_report_path,
        log_path=log_path,
        audit_skill=audit_skill,
        executor_model=executor_model,
    )


def _run_mock_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
) -> StageExecutionResult:
    if _sleep_with_cancel(hooks):
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=None,
            log_path=log_path,
            artifacts=[],
            session_files=[prompt_path],
            metadata={"executor_mode": "mock", "audit_skill": audit_skill},
        )
    report_body = "\n".join(
        [
            "# IPC Audit Report",
            "",
            f"- Task ID: `{context.task_id}`",
            f"- Attempt ID: `{context.attempt_id}`",
            f"- Workspace: `{context.workspace_id}`",
            f"- Project Path: `{context.project_path}`",
            f"- Audit Skill: `{audit_skill}`",
            "",
            "This is a scaffold report generated by the IPC audit service mock executor.",
            "",
            "## Prompt Snapshot",
            "",
            "```text",
            prompt,
            "```",
            "",
        ]
    )
    write_text_file(
        log_path,
        "\n".join(
            [
                f"=== {audit_skill} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Repo root: {context.repo_root}",
                f"Subproject: {context.project_path}",
                "=== prompt ===",
                prompt,
                "=== executor output ===",
                "[mock] audit stage completed",
                "",
            ]
        ),
    )
    write_text_file(last_message_path, report_body)
    write_text_file(final_report_path, report_body)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=0,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=[prompt_path, last_message_path],
        output_path=final_report_path,
        metadata={"executor_mode": "mock", "audit_skill": audit_skill},
    )


def _run_codex_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    output_path = _attempt_output_path(context)
    cfg = get_config().execution
    process_env, provider_summary, provider_metadata = build_process_env_and_summary(context)
    cmd = build_codex_exec_command(
        prompt,
        repo_root=context.repo_root,
        sandbox_mode=str(context.effective_config.get("audit_sandbox_mode") or get_config().execution.audit_sandbox_mode),
        approval_policy=str(context.effective_config.get("audit_approval_policy") or get_config().execution.audit_approval_policy),
        network_access=bool(context.effective_config.get("audit_network_access", get_config().execution.audit_network_access)),
        model=executor_model,
        add_dirs=[context.attempt_root],
        json_output=cfg.codex_json_output,
        output_last_message_path=last_message_path if cfg.codex_capture_last_message else None,
    )
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"Executor mode: codex_cli",
            f"Model: {executor_model or '(default)'}",
            f"Output report path: {output_path}",
            "=== provider runtime ===",
            provider_summary,
            "=== command ===",
            command_line_string(cmd),
            "=== prompt ===",
            prompt,
            "=== codex output ===" if not cfg.codex_json_output else "=== codex jsonl events ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=context.repo_root,
        log_path=log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(get_config().execution.task_timeout_seconds),
        mirror_output_paths=[events_path] if cfg.codex_json_output else None,
        process_env=process_env,
    )
    session_files = [prompt_path]
    if events_path.exists():
        session_files.append(events_path)
    if cfg.codex_capture_last_message and last_message_path.exists():
        session_files.append(last_message_path)
    if result.cancelled:
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
                **provider_metadata,
            },
        )
    if result.timed_out:
        return StageExecutionResult(
            stage_name="audit",
            status="timed_out",
            message="audit stage timed out",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
                **provider_metadata,
            },
        )
    if result.return_code != 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit stage failed with return code {result.return_code}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
                **provider_metadata,
            },
        )
    if not output_path.exists() or output_path.stat().st_size == 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit report not generated: {output_path}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
            },
        )
    copy_file(output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=result.return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=session_files,
        output_path=final_report_path,
        metadata={
            "executor_mode": "codex_cli",
            "model": executor_model,
            "audit_skill": audit_skill,
            "output_path": str(output_path),
            "duration_seconds": result.duration_seconds,
            **provider_metadata,
        },
    )


def _run_agentflow_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    if context.pipeline_mode != "audit_then_poc":
        return _run_agentflow_single_node_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
            executor_model=executor_model,
        )
    return _run_agentflow_combined_pipeline(
        context=context,
        hooks=hooks,
        prompt=prompt,
        prompt_path=prompt_path,
        events_path=events_path,
        last_message_path=last_message_path,
        final_report_path=final_report_path,
        log_path=log_path,
        audit_skill=audit_skill,
        executor_model=executor_model,
    )


def _run_agentflow_single_node_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    cfg = get_config().execution
    output_path = _attempt_output_path(context)
    sandbox_mode = str(context.effective_config.get("audit_sandbox_mode") or cfg.audit_sandbox_mode)
    network_access = bool(context.effective_config.get("audit_network_access", cfg.audit_network_access))
    pipeline_path = context.stage_session_dir() / "agentflow-pipeline.json"
    runs_dir = context.stage_session_dir() / "agentflow-runs"
    agent_name = cfg.agentflow_agent
    work_dir = resolve_stage_work_dir(context)
    pipeline_payload: dict[str, object] = {
        "name": f"secflow-ipc-audit-{context.stage_name}",
        "working_dir": str(work_dir),
        "nodes": [
            build_agentflow_node(
                node_id=context.stage_name,
                prompt=prompt,
                repo_root=context.repo_root,
                work_dir=work_dir,
                attempt_root=context.attempt_root,
                model=executor_model,
                sandbox_mode=sandbox_mode,
                network_access=network_access,
                success_criteria=[
                    {
                        "kind": "file_nonempty",
                        "path": str(output_path),
                    }
                ],
            )
        ],
    }
    write_json_file(pipeline_path, pipeline_payload)
    process_env, provider_summary, provider_metadata = build_agentflow_process_env_and_summary(context)
    process_env["AGENTFLOW_RUNS_DIR"] = str(runs_dir)
    cmd = build_agentflow_exec_command(pipeline_path, runs_dir=runs_dir)
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"AgentFlow work dir: {work_dir}",
            f"Executor mode: agentflow_cli",
            f"AgentFlow agent: {agent_name}",
            f"Model: {executor_model or '(default)'}",
            f"Output report path: {output_path}",
            "=== provider runtime ===",
            provider_summary,
            "=== command ===",
            command_line_string(cmd),
            "=== prompt ===",
            prompt,
            "=== agentflow cli output ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=work_dir,
        log_path=log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(cfg.task_timeout_seconds),
        process_env=process_env,
    )
    session_files = [prompt_path]
    run_dir = discover_single_run_dir(runs_dir)
    trace_path = run_dir / "artifacts" / context.stage_name / "trace.jsonl" if run_dir else None
    result_path = run_dir / "artifacts" / context.stage_name / "result.json" if run_dir else None
    stdout_path = run_dir / "artifacts" / context.stage_name / "stdout.log" if run_dir else None
    stderr_path = run_dir / "artifacts" / context.stage_name / "stderr.log" if run_dir else None
    if stdout_path and stdout_path.exists():
        append_file_to_log(log_path, stdout_path, "=== agentflow node stdout ===")
    if stderr_path and stderr_path.exists() and stderr_path.stat().st_size > 0:
        append_file_to_log(log_path, stderr_path, "=== agentflow node stderr ===")
    if trace_path and trace_path.exists():
        session_files.append(trace_path)
    if events_path.exists():
        session_files.append(events_path)
    if result_path and result_path.exists():
        write_last_message_from_agentflow_result(result_path, last_message_path)
    if last_message_path.exists():
        session_files.append(last_message_path)
    metadata = {
        "executor_mode": "agentflow_cli",
        "agentflow_agent": agent_name,
        "model": executor_model,
        "audit_skill": audit_skill,
        "output_path": str(output_path),
        "duration_seconds": result.duration_seconds,
        "agentflow_pipeline_path": str(pipeline_path),
        "agentflow_run_dir": str(run_dir) if run_dir else None,
        **provider_metadata,
    }
    if result.cancelled:
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.timed_out:
        return StageExecutionResult(
            stage_name="audit",
            status="timed_out",
            message="audit stage timed out",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.return_code != 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit stage failed with return code {result.return_code}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if not output_path.exists() or output_path.stat().st_size == 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit report not generated: {output_path}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    copy_file(output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=result.return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=session_files,
        output_path=final_report_path,
        metadata=metadata,
    )


def _run_agentflow_combined_pipeline(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    from app.workers import stage_poc as stage_poc_module

    cfg = get_config().execution
    audit_output_path = _attempt_output_path(context)
    poc_prompt_path = context.runtime_root / "poc" / "prompt.txt"
    poc_events_path = context.runtime_root / "poc" / "events.jsonl"
    poc_last_message_path = context.runtime_root / "poc" / "last-message.md"
    poc_log_path = context.logs_dir / "poc.codex.log"
    poc_output_report_path = stage_poc_module._attempt_output_report(context)
    poc_output_json_path = stage_poc_module._attempt_output_json(context)
    poc_prompt = stage_poc_module._build_prompt(
        poc_skill=str(context.effective_config.get("poc_skill") or cfg.default_poc_skill),
        repo_root=context.repo_root,
        source_report_path=audit_output_path,
        output_report_path=poc_output_report_path,
        output_json_path=poc_output_json_path,
        report_language=str(context.effective_config.get("report_language") or "zh-CN"),
        qemu_instance_name=stage_poc_module._poc_qemu_instance_name(context),
    )
    write_text_file(poc_prompt_path, poc_prompt)
    pipeline_path = context.runtime_root / "agentflow-stage-pipeline.json"
    runs_dir = context.runtime_root / "agentflow-runs"
    combined_cli_log_path = context.stage_session_dir() / "agentflow-cli.log"
    agent_name = cfg.agentflow_agent
    work_dir = resolve_stage_work_dir(context)
    stage_specs = [
        {
            "stage_name": "audit",
            "prompt": prompt,
            "prompt_path": prompt_path,
            "events_path": events_path,
            "last_message_path": last_message_path,
            "log_path": log_path,
            "output_paths": [audit_output_path],
            "node": build_agentflow_node(
                node_id="audit",
                prompt=prompt,
                repo_root=context.repo_root,
                work_dir=work_dir,
                attempt_root=context.attempt_root,
                model=executor_model,
                sandbox_mode=str(context.effective_config.get("audit_sandbox_mode") or cfg.audit_sandbox_mode),
                network_access=bool(context.effective_config.get("audit_network_access", cfg.audit_network_access)),
                success_criteria=[
                    {
                        "kind": "file_nonempty",
                        "path": str(audit_output_path),
                    }
                ],
            ),
            "header_lines": [
                f"=== {audit_skill} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Repo root: {context.repo_root}",
                f"Subproject: {context.project_path}",
                f"AgentFlow work dir: {work_dir}",
                "Executor mode: agentflow_cli",
                f"AgentFlow agent: {agent_name}",
                f"Model: {executor_model or '(default)'}",
                f"Output report path: {audit_output_path}",
                "=== prompt ===",
                prompt,
            ],
        },
        {
            "stage_name": "poc",
            "prompt": poc_prompt,
            "prompt_path": poc_prompt_path,
            "events_path": poc_events_path,
            "last_message_path": poc_last_message_path,
            "log_path": poc_log_path,
            "output_paths": [poc_output_report_path, poc_output_json_path],
            "node": build_agentflow_node(
                node_id="poc",
                prompt=poc_prompt,
                repo_root=context.repo_root,
                work_dir=work_dir,
                attempt_root=context.attempt_root,
                model=executor_model,
                sandbox_mode=str(context.effective_config.get("poc_sandbox_mode") or cfg.poc_sandbox_mode),
                network_access=bool(context.effective_config.get("poc_network_access", cfg.poc_network_access)),
                depends_on=["audit"],
                success_criteria=[
                    {
                        "kind": "file_nonempty",
                        "path": str(poc_output_report_path),
                    },
                    {
                        "kind": "file_nonempty",
                        "path": str(poc_output_json_path),
                    },
                    {
                        "kind": "json_valid",
                        "path": str(poc_output_json_path),
                    },
                ],
            ),
            "header_lines": [
                f"=== {str(context.effective_config.get('poc_skill') or cfg.default_poc_skill)} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Repo root: {context.repo_root}",
                f"AgentFlow work dir: {work_dir}",
                f"Source report: {audit_output_path}",
                "Executor mode: agentflow_cli",
                f"AgentFlow agent: {agent_name}",
                f"Model: {executor_model or '(default)'}",
                f"Output PoC report path: {poc_output_report_path}",
                f"Output audited result json path: {poc_output_json_path}",
                "=== prompt ===",
                poc_prompt,
            ],
        },
    ]
    pipeline_payload: dict[str, object] = {
        "name": "secflow-ipc-audit-stage-pipeline",
        "working_dir": str(work_dir),
        "nodes": [stage_spec["node"] for stage_spec in stage_specs],
    }
    write_json_file(pipeline_path, pipeline_payload)
    process_env, provider_summary, provider_metadata = build_agentflow_process_env_and_summary(context)
    process_env["AGENTFLOW_RUNS_DIR"] = str(runs_dir)
    cmd = build_agentflow_exec_command(pipeline_path, runs_dir=runs_dir)
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"AgentFlow work dir: {work_dir}",
            "Executor mode: agentflow_cli",
            f"AgentFlow agent: {agent_name}",
            f"Model: {executor_model or '(default)'}",
            f"Audit output report path: {audit_output_path}",
            f"PoC output report path: {poc_output_report_path}",
            f"PoC output audited result json path: {poc_output_json_path}",
            "=== provider runtime ===",
            provider_summary,
            "=== command ===",
            command_line_string(cmd),
            "=== audit prompt ===",
            prompt,
            "=== poc prompt ===",
            poc_prompt,
            "=== agentflow cli output ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=work_dir,
        log_path=combined_cli_log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(cfg.task_timeout_seconds),
        process_env=process_env,
    )
    run_dir = discover_single_run_dir(runs_dir)
    materialized_stages = {
        str(stage_spec["stage_name"]): _materialize_agentflow_combined_stage(
            stage_name=str(stage_spec["stage_name"]),
            stage_prompt=str(stage_spec["prompt"]),
            stage_log_path=stage_spec["log_path"],
            prompt_path=stage_spec["prompt_path"],
            events_path=stage_spec["events_path"],
            last_message_path=stage_spec["last_message_path"],
            output_paths=stage_spec["output_paths"],
            combined_cli_log_path=combined_cli_log_path,
            run_dir=run_dir,
            process_result=result,
            header_lines=stage_spec["header_lines"],
        )
        for stage_spec in stage_specs
    }
    audit_stage_data = materialized_stages["audit"]
    manifest_path = _agentflow_manifest_path(context)
    write_json_file(
        manifest_path,
        {
            "kind": "combined_stage_pipeline",
            "pipeline_path": str(pipeline_path),
            "run_dir": str(run_dir) if run_dir else None,
            "process": {
                "return_code": result.return_code,
                "cancelled": result.cancelled,
                "timed_out": result.timed_out,
                "duration_seconds": result.duration_seconds,
            },
            "stages": materialized_stages,
        },
    )
    metadata = {
        "executor_mode": "agentflow_cli",
        "agentflow_agent": agent_name,
        "model": executor_model,
        "audit_skill": audit_skill,
        "output_path": str(audit_output_path),
        "duration_seconds": result.duration_seconds,
        "agentflow_pipeline_path": str(pipeline_path),
        "agentflow_run_dir": str(run_dir) if run_dir else None,
        "agentflow_manifest_path": str(manifest_path),
        **provider_metadata,
    }
    audit_session_files = [prompt_path]
    audit_trace_path = Path(str(audit_stage_data.get("trace_path") or ""))
    if str(audit_stage_data.get("trace_path") or "") and audit_trace_path.exists():
        audit_session_files.append(audit_trace_path)
    if events_path.exists():
        audit_session_files.append(events_path)
    if last_message_path.exists():
        audit_session_files.append(last_message_path)
    audit_stage_status = str(audit_stage_data.get("status") or "failed")
    audit_return_code = audit_stage_data.get("return_code")
    audit_message = str(audit_stage_data.get("message") or "audit stage failed")
    if audit_stage_status != "succeeded":
        return StageExecutionResult(
            stage_name="audit",
            status=audit_stage_status,
            message=audit_message,
            return_code=audit_return_code,
            log_path=log_path,
            artifacts=[],
            session_files=audit_session_files,
            metadata=metadata,
        )
    copy_file(audit_output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=audit_return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=audit_session_files,
        output_path=final_report_path,
        metadata=metadata,
    )


def _materialize_agentflow_combined_stage(
    *,
    stage_name: str,
    stage_prompt: str,
    stage_log_path: Path,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    output_paths: list[Path],
    combined_cli_log_path: Path,
    run_dir: Path | None,
    process_result,
    header_lines: list[str],
) -> dict[str, Any]:
    stage_artifact_dir = run_dir / "artifacts" / stage_name if run_dir else None
    trace_path = stage_artifact_dir / "trace.jsonl" if stage_artifact_dir else None
    result_path = stage_artifact_dir / "result.json" if stage_artifact_dir else None
    stdout_path = stage_artifact_dir / "stdout.log" if stage_artifact_dir else None
    stderr_path = stage_artifact_dir / "stderr.log" if stage_artifact_dir else None
    if result_path and result_path.exists():
        write_last_message_from_agentflow_result(result_path, last_message_path)
    stage_result_payload = read_json_file(result_path) if result_path else None
    node_status = str(stage_result_payload.get("status") or "").strip().lower() if isinstance(stage_result_payload, dict) else ""
    return_code = (
        stage_result_payload.get("exit_code")
        if isinstance(stage_result_payload, dict) and stage_result_payload.get("exit_code") is not None
        else process_result.return_code
    )
    if node_status == "completed":
        if any(not path.exists() or path.stat().st_size == 0 for path in output_paths):
            status = "failed"
            message = f"{stage_name} stage outputs not generated"
        else:
            status = "succeeded"
            message = f"{stage_name} stage completed"
    elif node_status == "cancelled" or process_result.cancelled:
        status = "cancelled"
        message = f"{stage_name} stage cancelled"
    elif process_result.timed_out:
        status = "timed_out"
        message = f"{stage_name} stage timed out"
    elif node_status == "failed":
        status = "failed"
        message = f"{stage_name} stage failed"
    else:
        status = "failed"
        message = f"{stage_name} stage failed"
    write_text_file(stage_log_path, "\n".join(header_lines) + "\n")
    if combined_cli_log_path.exists():
        append_file_to_log(stage_log_path, combined_cli_log_path, "=== agentflow cli output ===")
    if stdout_path and stdout_path.exists():
        append_file_to_log(stage_log_path, stdout_path, "=== agentflow node stdout ===")
    if stderr_path and stderr_path.exists() and stderr_path.stat().st_size > 0:
        append_file_to_log(stage_log_path, stderr_path, "=== agentflow node stderr ===")
    return {
        "stage_name": stage_name,
        "status": status,
        "message": message,
        "return_code": return_code,
        "prompt_path": str(prompt_path),
        "events_path": str(events_path),
        "last_message_path": str(last_message_path),
        "log_path": str(stage_log_path),
        "output_paths": [str(path) for path in output_paths],
        "result_path": str(result_path) if result_path else None,
        "trace_path": str(trace_path) if trace_path else None,
        "stdout_path": str(stdout_path) if stdout_path else None,
        "stderr_path": str(stderr_path) if stderr_path else None,
        "prompt": stage_prompt,
    }


def _agentflow_manifest_path(context: StageContext) -> Path:
    return context.runtime_root / "agentflow-stage-pipeline-manifest.json"


def _run_opencode_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    output_path = _attempt_output_path(context)
    process_env, provider_summary, provider_metadata = build_process_env_and_summary(context)
    cmd = build_opencode_exec_command(
        prompt,
        repo_root=context.repo_root,
        model=executor_model,
        json_output=True,
    )
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"Executor mode: opencode_cli",
            f"Model: {executor_model or '(default)'}",
            f"Output report path: {output_path}",
            "=== provider runtime ===",
            provider_summary,
            "=== command ===",
            command_line_string(cmd),
            "=== prompt ===",
            prompt,
            "=== opencode jsonl events ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=context.repo_root,
        log_path=log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(get_config().execution.task_timeout_seconds),
        mirror_output_paths=[events_path],
        process_env=process_env,
    )
    retry_count = 0
    total_duration = result.duration_seconds
    session_id = extract_opencode_session_id(events_path)
    max_retries = max(int(get_config().execution.opencode_missing_output_max_retries), 0)
    while (
        not result.cancelled
        and not result.timed_out
        and session_id
        and retry_count < max_retries
    ):
        output_missing = _missing_output(output_path)
        last_event_error = opencode_last_event_is_error(events_path)
        if not ((result.return_code == 0 and output_missing) or last_event_error):
            break
        retry_count += 1
        retry_reason = "opencode_last_error" if last_event_error else "missing_output"
        previous_return_code = result.return_code
        retry_prompt = _build_missing_audit_output_retry_prompt(
            repo_root=context.repo_root,
            project_path=str(resolve_stage_work_dir(context)) if context.project_path else "",
            output_report_path=output_path,
            retry_count=retry_count,
            max_retries=max_retries,
            retry_reason=retry_reason,
        )
        retry_cmd = build_opencode_exec_command(
            retry_prompt,
            repo_root=context.repo_root,
            model=executor_model,
            json_output=True,
            session_id=session_id,
        )
        retry_header = "\n".join(
            [
                "",
                f"=== opencode recovery retry {retry_count}/{max_retries} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Session ID: {session_id}",
                f"Retry reason: {retry_reason}",
                f"Previous return code: {previous_return_code}",
                f"Output report path: {output_path}",
                "=== provider runtime ===",
                provider_summary,
                "=== command ===",
                command_line_string(retry_cmd),
                "=== retry prompt ===",
                retry_prompt,
                "=== opencode jsonl events ===",
                "",
            ]
        )
        result = run_logged_command(
            retry_cmd,
            cwd=context.repo_root,
            log_path=log_path,
            log_header=retry_header,
            hooks=hooks,
            timeout_seconds=int(get_config().execution.task_timeout_seconds),
            mirror_output_paths=[events_path],
            append=True,
            process_env=process_env,
        )
        total_duration += result.duration_seconds
    session_files = [prompt_path]
    if events_path.exists():
        session_files.append(events_path)
    if write_last_message_from_jsonl(events_path, last_message_path) is not None:
        session_files.append(last_message_path)
    metadata = {
        "executor_mode": "opencode_cli",
        "model": executor_model,
        "audit_skill": audit_skill,
        "output_path": str(output_path),
        "duration_seconds": total_duration,
        "opencode_session_id": session_id,
        "opencode_recovery_retry_count": retry_count,
        "missing_output_retry_count": retry_count,
        "opencode_last_event_error": opencode_last_event_is_error(events_path),
        **provider_metadata,
    }
    if result.cancelled:
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.timed_out:
        return StageExecutionResult(
            stage_name="audit",
            status="timed_out",
            message="audit stage timed out",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.return_code != 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit stage failed with return code {result.return_code}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if not output_path.exists() or output_path.stat().st_size == 0:
        retry_suffix = f" after {retry_count} same-session retries" if retry_count else ""
        session_suffix = "" if session_id else " (opencode session id unavailable)"
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit report not generated{retry_suffix}{session_suffix}: {output_path}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    copy_file(output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=result.return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=session_files,
        output_path=final_report_path,
        metadata=metadata,
    )


def _build_prompt(*, audit_skill: str, repo_root: Path, project_path: str, output_report_path: Path) -> str:
    return "\n".join(
        [
            "OpenHarmony IPC deep OOB audit task.",
            f"Embedded workflow profile: {audit_skill}",
            f"Repo root: {repo_root}",
            f"Subproject: {project_path}",
            f"Output report path: {output_report_path}",
            "",
            _AUDIT_WORKFLOW_PROMPT,
        ]
    )


def _build_missing_audit_output_retry_prompt(
    *,
    repo_root: Path,
    project_path: str,
    output_report_path: Path,
    retry_count: int,
    max_retries: int,
    retry_reason: str,
) -> str:
    reason_text = "The previous command exited successfully, but the required Markdown report file was not created."
    if retry_reason == "opencode_last_error":
        reason_text = "The previous OpenCode command ended with an error event in its JSONL stream, so the stage did not finish cleanly."
    return "\n".join(
        [
            "Continue the same OpenHarmony IPC audit session.",
            f"Retry: {retry_count}/{max_retries}",
            f"Retry reason: {retry_reason}",
            f"Repo root: {repo_root}",
            f"Subproject: {project_path}",
            f"Required output report path: {output_report_path}",
            "",
            reason_text,
            "Do not restart the task or ask for clarification. Continue from the existing session context.",
            "Inspect more files only if needed, then create parent directories and write the final Markdown report exactly to the required output report path.",
            "Keep any additional search scoped to the Subproject path. Do not run broad rg/find searches from Repo root.",
            "Before your final response, verify that the report file exists and is non-empty.",
            "If no issue is found, the report must still be written and must explicitly say no concrete IPC-reachable OOB issue was found.",
        ]
    )


def _attempt_output_path(context: StageContext) -> Path:
    label = project_label(context.project_path or "audit-report")
    return context.stage_session_dir() / "outputs" / f"{label}.md"


def _missing_output(path: Path) -> bool:
    return not path.exists() or path.stat().st_size == 0


def _sleep_with_cancel(hooks: StageHooks) -> bool:
    delay = max(float(get_config().execution.mock_stage_delay_seconds), 0.0)
    if delay <= 0:
        return hooks.is_cancel_requested()
    started = time.monotonic()
    while time.monotonic() - started < delay:
        hooks.heartbeat()
        if hooks.is_cancel_requested():
            return True
        time.sleep(min(0.2, delay))
    return hooks.is_cancel_requested()


_AUDIT_WORKFLOW_PROMPT = """\
This prompt is self-contained. Do not invoke, require, or assume any external Codex/OpenCode skill.

Goal:
- Audit only the specified OpenHarmony subproject for IPC-reachable out-of-bounds memory reads/writes.
- Stay scoped to the subproject source for candidate surfaces and broad searches.
- Do not use rg/find from Repo root to discover candidates. If readtags or a direct code reference points to a file outside the subproject, read that exact file directly as dependency context only.
- Write the final Markdown report exactly to Output report path. Create parent directories if needed.

Workflow:
1. Find IPC-reachable attack surfaces first.
- Search under the subproject for server-side IPC handlers and parcel consumers: OnRemoteRequest, OnRemoteRequestInner, IRemoteStub, RemoteStub, IPCObjectStub, transaction dispatch switches/tables, and helpers that read MessageParcel/data.
- Prefer rg under the subproject first. Exclude tests, fuzzers, demos, and sample code unless they reveal the production path.
- The process cwd is intended to be the Subproject path. Do not cd to Repo root or run bare rg/find there.
- Do not run broad rg searches from Repo root. Repo-root access is only for reading exact files resolved by readtags or already referenced from the subproject code.

2. Resolve real implementations; never guess.
- When a relevant function or class is declared, generated, virtual, or referenced indirectly, resolve its real implementation before judging safety.
- Prefer readtags against the Repo root tags file when available: readtags -e -t <Repo root>/tags <symbol> | grep -v test.
- If readtags returns definitions in another project, open those returned files directly. Do not use repo-wide rg to rediscover or expand the search.
- If an implementation cannot be found, record it in an Unresolved section and do not claim a vulnerability based on assumptions.

3. Build the full serialization/deserialization object graph.
- For each IPC transaction, enumerate every parcel read in order: scalar fields, strings, vectors, arrays, maps, file descriptors, raw buffers, blobs, shared memory, ReadParcelable/ReadStrongParcelable, Unmarshalling, ReadFromParcel, and helper parsers.
- For each reconstructed object, inspect field validation, nested member types, constructors, setters, normalizers, conversion helpers, and later consumers.
- Treat all deserialized fields as attacker-controlled until a relevant invariant is proven.

4. Report only concrete OOB read/write issues.
- A valid finding needs this chain: attacker controls IPC parcel data; validation is missing/incomplete or invalidated later; tainted value reaches index/offset/length/stride/count/copy arithmetic; the use can cross the target object's or buffer's bounds.
- Do not report permission issues, null dereference, use-after-free, double free, memory leaks, gradual resource exhaustion, or pure integer overflow unless they are necessary to prove a concrete OOB read/write.

5. Trace into dependent classes and sinks.
- Follow tainted fields beyond the immediate MessageParcel reader into business logic, storage classes, codecs, TLV parsers, flatten/unflatten code, and custom binary parsers.
- Pay special attention to size/count/length/capacity/offset/stride/index/start/end fields, paired offset+length or width+height+stride fields, enum/tag controlled decoding, raw pointers/views, and container sizes trusted before indexing/copying.
- Inspect sinks such as memcpy, memmove, memset, strncpy-like helpers, manual pointer arithmetic, subspan slicing, vector/array/string indexing, and loops controlled by parcel-derived counts.

6. Demand concrete evidence.
- Cite exact attacker-controlled parcel fields and exact later OOB sinks.
- Include file paths and line numbers wherever possible.
- If safety depends on an assumption you cannot prove from code, mark the path unresolved instead of reporting it.
- Keep external files resolved by readtags clearly marked as dependency context, not as new audit scope.

Report requirements:
- Include Scope: Repo root, Subproject, audited IPC entrypoints, and transaction codes if known.
- For each finding include title, severity, affected IPC entrypoint/transaction path, deserialization chain, dependent class/helper chain, concrete OOB sink, attacker-controlled fields, impact, evidence, exploitability notes, and suggested fix.
- If no issue is found, say so explicitly and summarize the IPC surfaces and object graphs inspected.
- Add an Unresolved section for missing definitions or uncertain paths, including the exact rg/readtags attempts made.
"""
