from __future__ import annotations

import time
from pathlib import Path

from app.core.config import get_config
from app.core.time_utils import utc_now_z
from app.workers.runner import (
    StageArtifact,
    StageContext,
    StageExecutionResult,
    StageHooks,
    build_codex_exec_command,
    build_opencode_exec_command,
    command_line_string,
    copy_file,
    extract_opencode_session_id,
    opencode_last_event_is_error,
    project_label,
    resolve_executor_mode,
    resolve_executor_model,
    run_logged_command,
    write_last_message_from_jsonl,
    write_text_file,
)


def run_audit_stage(context: StageContext, hooks: StageHooks) -> StageExecutionResult:
    cfg = get_config().execution
    audit_skill = str(context.effective_config.get("audit_skill") or cfg.default_audit_skill)
    executor_mode = resolve_executor_mode(context.effective_config)
    executor_model = resolve_executor_model(context.effective_config)
    prompt_path = context.stage_session_file("prompt.txt")
    events_path = context.stage_session_file("events.jsonl")
    last_message_path = context.stage_session_file("last-message.md")
    final_report_path = context.stage_artifact_path("audit-report.md")
    log_path = context.stage_log_path()
    prompt = _build_prompt(
        audit_skill=audit_skill,
        repo_root=context.repo_root,
        project_path=context.project_path or "",
        output_report_path=_attempt_output_path(context),
    )
    write_text_file(prompt_path, prompt)

    if executor_mode == "mock":
        return _run_mock_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
        )
    if executor_mode == "opencode_cli":
        return _run_opencode_stage(
            context=context,
            hooks=hooks,
            prompt=prompt,
            prompt_path=prompt_path,
            events_path=events_path,
            last_message_path=last_message_path,
            final_report_path=final_report_path,
            log_path=log_path,
            audit_skill=audit_skill,
            executor_model=executor_model,
        )
    return _run_codex_stage(
        context=context,
        hooks=hooks,
        prompt=prompt,
        prompt_path=prompt_path,
        events_path=events_path,
        last_message_path=last_message_path,
        final_report_path=final_report_path,
        log_path=log_path,
        audit_skill=audit_skill,
        executor_model=executor_model,
    )


def _run_mock_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
) -> StageExecutionResult:
    if _sleep_with_cancel(hooks):
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=None,
            log_path=log_path,
            artifacts=[],
            session_files=[prompt_path],
            metadata={"executor_mode": "mock", "audit_skill": audit_skill},
        )
    report_body = "\n".join(
        [
            "# IPC Audit Report",
            "",
            f"- Task ID: `{context.task_id}`",
            f"- Attempt ID: `{context.attempt_id}`",
            f"- Workspace: `{context.workspace_id}`",
            f"- Project Path: `{context.project_path}`",
            f"- Audit Skill: `{audit_skill}`",
            "",
            "This is a scaffold report generated by the IPC audit service mock executor.",
            "",
            "## Prompt Snapshot",
            "",
            "```text",
            prompt,
            "```",
            "",
        ]
    )
    write_text_file(
        log_path,
        "\n".join(
            [
                f"=== {audit_skill} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Repo root: {context.repo_root}",
                f"Subproject: {context.project_path}",
                "=== prompt ===",
                prompt,
                "=== executor output ===",
                "[mock] audit stage completed",
                "",
            ]
        ),
    )
    write_text_file(events_path, "")
    write_text_file(last_message_path, report_body)
    write_text_file(final_report_path, report_body)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=0,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=[prompt_path, events_path, last_message_path],
        output_path=final_report_path,
        metadata={"executor_mode": "mock", "audit_skill": audit_skill},
    )


def _run_codex_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    output_path = _attempt_output_path(context)
    cfg = get_config().execution
    cmd = build_codex_exec_command(
        prompt,
        repo_root=context.repo_root,
        sandbox_mode=str(context.effective_config.get("audit_sandbox_mode") or get_config().execution.audit_sandbox_mode),
        approval_policy=str(context.effective_config.get("audit_approval_policy") or get_config().execution.audit_approval_policy),
        network_access=bool(context.effective_config.get("audit_network_access", get_config().execution.audit_network_access)),
        model=executor_model,
        add_dirs=[context.attempt_root],
        json_output=cfg.codex_json_output,
        output_last_message_path=last_message_path if cfg.codex_capture_last_message else None,
    )
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"Executor mode: codex_cli",
            f"Model: {executor_model or '(default)'}",
            f"Output report path: {output_path}",
            "=== command ===",
            command_line_string(cmd),
            "=== prompt ===",
            prompt,
            "=== codex output ===" if not cfg.codex_json_output else "=== codex jsonl events ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=context.repo_root,
        log_path=log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(get_config().execution.task_timeout_seconds),
        mirror_output_paths=[events_path] if cfg.codex_json_output else None,
    )
    session_files = [prompt_path]
    if events_path.exists():
        session_files.append(events_path)
    if cfg.codex_capture_last_message and last_message_path.exists():
        session_files.append(last_message_path)
    if result.cancelled:
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
            },
        )
    if result.timed_out:
        return StageExecutionResult(
            stage_name="audit",
            status="timed_out",
            message="audit stage timed out",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
            },
        )
    if result.return_code != 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit stage failed with return code {result.return_code}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
            },
        )
    if not output_path.exists() or output_path.stat().st_size == 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit report not generated: {output_path}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata={
                "executor_mode": "codex_cli",
                "model": executor_model,
                "audit_skill": audit_skill,
                "output_path": str(output_path),
                "duration_seconds": result.duration_seconds,
            },
        )
    copy_file(output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=result.return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=session_files,
        output_path=final_report_path,
        metadata={
            "executor_mode": "codex_cli",
            "model": executor_model,
            "audit_skill": audit_skill,
            "output_path": str(output_path),
            "duration_seconds": result.duration_seconds,
        },
    )


def _run_opencode_stage(
    *,
    context: StageContext,
    hooks: StageHooks,
    prompt: str,
    prompt_path: Path,
    events_path: Path,
    last_message_path: Path,
    final_report_path: Path,
    log_path: Path,
    audit_skill: str,
    executor_model: str | None,
) -> StageExecutionResult:
    output_path = _attempt_output_path(context)
    cmd = build_opencode_exec_command(
        prompt,
        repo_root=context.repo_root,
        model=executor_model,
        json_output=True,
    )
    log_header = "\n".join(
        [
            f"=== {audit_skill} ===",
            f"Generated at (UTC): {utc_now_z()}",
            f"Repo root: {context.repo_root}",
            f"Subproject: {context.project_path}",
            f"Executor mode: opencode_cli",
            f"Model: {executor_model or '(default)'}",
            f"Output report path: {output_path}",
            "=== command ===",
            command_line_string(cmd),
            "=== prompt ===",
            prompt,
            "=== opencode jsonl events ===",
            "",
        ]
    )
    result = run_logged_command(
        cmd,
        cwd=context.repo_root,
        log_path=log_path,
        log_header=log_header,
        hooks=hooks,
        timeout_seconds=int(get_config().execution.task_timeout_seconds),
        mirror_output_paths=[events_path],
    )
    retry_count = 0
    total_duration = result.duration_seconds
    session_id = extract_opencode_session_id(events_path)
    max_retries = max(int(get_config().execution.opencode_missing_output_max_retries), 0)
    while (
        not result.cancelled
        and not result.timed_out
        and session_id
        and retry_count < max_retries
    ):
        output_missing = _missing_output(output_path)
        last_event_error = opencode_last_event_is_error(events_path)
        if not ((result.return_code == 0 and output_missing) or last_event_error):
            break
        retry_count += 1
        retry_reason = "opencode_last_error" if last_event_error else "missing_output"
        previous_return_code = result.return_code
        retry_prompt = _build_missing_audit_output_retry_prompt(
            repo_root=context.repo_root,
            project_path=context.project_path or "",
            output_report_path=output_path,
            retry_count=retry_count,
            max_retries=max_retries,
            retry_reason=retry_reason,
        )
        retry_cmd = build_opencode_exec_command(
            retry_prompt,
            repo_root=context.repo_root,
            model=executor_model,
            json_output=True,
            session_id=session_id,
        )
        retry_header = "\n".join(
            [
                "",
                f"=== opencode recovery retry {retry_count}/{max_retries} ===",
                f"Generated at (UTC): {utc_now_z()}",
                f"Session ID: {session_id}",
                f"Retry reason: {retry_reason}",
                f"Previous return code: {previous_return_code}",
                f"Output report path: {output_path}",
                "=== command ===",
                command_line_string(retry_cmd),
                "=== retry prompt ===",
                retry_prompt,
                "=== opencode jsonl events ===",
                "",
            ]
        )
        result = run_logged_command(
            retry_cmd,
            cwd=context.repo_root,
            log_path=log_path,
            log_header=retry_header,
            hooks=hooks,
            timeout_seconds=int(get_config().execution.task_timeout_seconds),
            mirror_output_paths=[events_path],
            append=True,
        )
        total_duration += result.duration_seconds
    session_files = [prompt_path]
    if events_path.exists():
        session_files.append(events_path)
    if write_last_message_from_jsonl(events_path, last_message_path) is not None:
        session_files.append(last_message_path)
    metadata = {
        "executor_mode": "opencode_cli",
        "model": executor_model,
        "audit_skill": audit_skill,
        "output_path": str(output_path),
        "duration_seconds": total_duration,
        "opencode_session_id": session_id,
        "opencode_recovery_retry_count": retry_count,
        "missing_output_retry_count": retry_count,
        "opencode_last_event_error": opencode_last_event_is_error(events_path),
    }
    if result.cancelled:
        return StageExecutionResult(
            stage_name="audit",
            status="cancelled",
            message="audit stage cancelled",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.timed_out:
        return StageExecutionResult(
            stage_name="audit",
            status="timed_out",
            message="audit stage timed out",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if result.return_code != 0:
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit stage failed with return code {result.return_code}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    if not output_path.exists() or output_path.stat().st_size == 0:
        retry_suffix = f" after {retry_count} same-session retries" if retry_count else ""
        session_suffix = "" if session_id else " (opencode session id unavailable)"
        return StageExecutionResult(
            stage_name="audit",
            status="failed",
            message=f"audit report not generated{retry_suffix}{session_suffix}: {output_path}",
            return_code=result.return_code,
            log_path=log_path,
            artifacts=[],
            session_files=session_files,
            metadata=metadata,
        )
    copy_file(output_path, final_report_path)
    return StageExecutionResult(
        stage_name="audit",
        status="succeeded",
        message="audit stage completed",
        return_code=result.return_code,
        log_path=log_path,
        artifacts=[StageArtifact("audit_report", final_report_path, display_name=final_report_path.name)],
        session_files=session_files,
        output_path=final_report_path,
        metadata=metadata,
    )


def _build_prompt(*, audit_skill: str, repo_root: Path, project_path: str, output_report_path: Path) -> str:
    return "\n".join(
        [
            "OpenHarmony IPC deep OOB audit task.",
            f"Embedded workflow profile: {audit_skill}",
            f"Repo root: {repo_root}",
            f"Subproject: {project_path}",
            f"Output report path: {output_report_path}",
            "",
            _AUDIT_WORKFLOW_PROMPT,
        ]
    )


def _build_missing_audit_output_retry_prompt(
    *,
    repo_root: Path,
    project_path: str,
    output_report_path: Path,
    retry_count: int,
    max_retries: int,
    retry_reason: str,
) -> str:
    reason_text = "The previous command exited successfully, but the required Markdown report file was not created."
    if retry_reason == "opencode_last_error":
        reason_text = "The previous OpenCode command ended with an error event in its JSONL stream, so the stage did not finish cleanly."
    return "\n".join(
        [
            "Continue the same OpenHarmony IPC audit session.",
            f"Retry: {retry_count}/{max_retries}",
            f"Retry reason: {retry_reason}",
            f"Repo root: {repo_root}",
            f"Subproject: {project_path}",
            f"Required output report path: {output_report_path}",
            "",
            reason_text,
            "Do not restart the task or ask for clarification. Continue from the existing session context.",
            "Inspect more files only if needed, then create parent directories and write the final Markdown report exactly to the required output report path.",
            "Before your final response, verify that the report file exists and is non-empty.",
            "If no issue is found, the report must still be written and must explicitly say no concrete IPC-reachable OOB issue was found.",
        ]
    )


def _attempt_output_path(context: StageContext) -> Path:
    label = project_label(context.project_path or "audit-report")
    return context.stage_session_dir() / "outputs" / f"{label}.md"


def _missing_output(path: Path) -> bool:
    return not path.exists() or path.stat().st_size == 0


def _sleep_with_cancel(hooks: StageHooks) -> bool:
    delay = max(float(get_config().execution.mock_stage_delay_seconds), 0.0)
    if delay <= 0:
        return hooks.is_cancel_requested()
    started = time.monotonic()
    while time.monotonic() - started < delay:
        hooks.heartbeat()
        if hooks.is_cancel_requested():
            return True
        time.sleep(min(0.2, delay))
    return hooks.is_cancel_requested()


_AUDIT_WORKFLOW_PROMPT = """\
This prompt is self-contained. Do not invoke, require, or assume any external Codex/OpenCode skill.

Goal:
- Audit only the specified OpenHarmony subproject for IPC-reachable out-of-bounds memory reads/writes.
- Stay scoped to the subproject for candidate surfaces, but follow call chains to real implementations anywhere under Repo root when needed.
- Write the final Markdown report exactly to Output report path. Create parent directories if needed.

Workflow:
1. Find IPC-reachable attack surfaces first.
- Search under the subproject for server-side IPC handlers and parcel consumers: OnRemoteRequest, OnRemoteRequestInner, IRemoteStub, RemoteStub, IPCObjectStub, transaction dispatch switches/tables, and helpers that read MessageParcel/data.
- Prefer rg under the subproject first. Exclude tests, fuzzers, demos, and sample code unless they reveal the production path.

2. Resolve real implementations; never guess.
- When a relevant function or class is declared, generated, virtual, or referenced indirectly, resolve its real implementation before judging safety.
- Prefer readtags against the Repo root tags file when available: readtags -e -t <Repo root>/tags <symbol> | grep -v test.
- If an implementation cannot be found, record it in an Unresolved section and do not claim a vulnerability based on assumptions.

3. Build the full serialization/deserialization object graph.
- For each IPC transaction, enumerate every parcel read in order: scalar fields, strings, vectors, arrays, maps, file descriptors, raw buffers, blobs, shared memory, ReadParcelable/ReadStrongParcelable, Unmarshalling, ReadFromParcel, and helper parsers.
- For each reconstructed object, inspect field validation, nested member types, constructors, setters, normalizers, conversion helpers, and later consumers.
- Treat all deserialized fields as attacker-controlled until a relevant invariant is proven.

4. Report only concrete OOB read/write issues.
- A valid finding needs this chain: attacker controls IPC parcel data; validation is missing/incomplete or invalidated later; tainted value reaches index/offset/length/stride/count/copy arithmetic; the use can cross the target object's or buffer's bounds.
- Do not report permission issues, null dereference, use-after-free, double free, memory leaks, gradual resource exhaustion, or pure integer overflow unless they are necessary to prove a concrete OOB read/write.

5. Trace into dependent classes and sinks.
- Follow tainted fields beyond the immediate MessageParcel reader into business logic, storage classes, codecs, TLV parsers, flatten/unflatten code, and custom binary parsers.
- Pay special attention to size/count/length/capacity/offset/stride/index/start/end fields, paired offset+length or width+height+stride fields, enum/tag controlled decoding, raw pointers/views, and container sizes trusted before indexing/copying.
- Inspect sinks such as memcpy, memmove, memset, strncpy-like helpers, manual pointer arithmetic, subspan slicing, vector/array/string indexing, and loops controlled by parcel-derived counts.

6. Demand concrete evidence.
- Cite exact attacker-controlled parcel fields and exact later OOB sinks.
- Include file paths and line numbers wherever possible.
- If safety depends on an assumption you cannot prove from code, mark the path unresolved instead of reporting it.

Report requirements:
- Include Scope: Repo root, Subproject, audited IPC entrypoints, and transaction codes if known.
- For each finding include title, severity, affected IPC entrypoint/transaction path, deserialization chain, dependent class/helper chain, concrete OOB sink, attacker-controlled fields, impact, evidence, exploitability notes, and suggested fix.
- If no issue is found, say so explicitly and summarize the IPC surfaces and object graphs inspected.
- Add an Unresolved section for missing definitions or uncertain paths, including the exact rg/readtags attempts made.
"""
