apiVersion: v1
kind: Service
metadata:
  name: secflow-app-poc-gen-verify-redis
  namespace: secflow-ns
  labels: { name: secflow-app-poc-gen-verify, component: redis }
spec:
  type: ClusterIP
  selector: { name: secflow-app-poc-gen-verify, component: redis }
  ports:
    - { name: redis, port: 6379, targetPort: 6379, protocol: TCP }
