apiVersion: v1
kind: Secret
metadata:
  name: secflow-app-poc-gen-verify-mysql-secret
  namespace: secflow-ns
  labels: { name: secflow-app-poc-gen-verify, component: mysql }
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Huawei12#$"
  MYSQL_ROOT_HOST: "%"
  MYSQL_DATABASE: "secflow_poc_gen_verify"
  MYSQL_USER: "secflow_poc_gen_verify"
  MYSQL_PASSWORD: "Huawei12#$"
  MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
  MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
