name: build-remote-command-api-image
on:
  push:
    branches:
      - 'v2.*'
    paths:
      - .github/workflows/build-remote-command-api-image.yml
      - 100-agent-service-image/01-remote-command-api/*
jobs:
  build-remote-command-api-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push remote-command-api-image
        uses: docker/build-push-action@v5
        with:
          context: 100-agent-service-image/01-remote-command-api/*
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v5
          push: true
          tags: |
            runshine0819/remote-command-api:latest
            ghcr.io/runshine/remote-command-api:latest
          file: 100-agent-service-image/01-remote-command-api/Dockerfile